operations upgrade

diff --git a/bin/operations b/bin/operations
--- a/bin/operations
+++ b/bin/operations
@@ -55,6 +55,11 @@ Commands:
         --no-tests - won't run the test suite upon release. Not usually recommended, unless we're
           releasing a snapshot.
 
+    build
+
+        Build the "releasable" artifact,  which usually is a self-contained, ready-to-install zip.
+        In case of a library,  is the JAR file (or the library)  as installed in a repository such
+        as Maven.
 
     install [-f|--force]
 
@@ -105,7 +110,7 @@ function main() {
         ((i++))
     done
 
-    [ "${command}" = "" ] && { usage; exit 0; }
+    [ "${command}" = "" -o "${arguments[0]}" = "--help" ] && { usage; exit 0; }
 
     #
     # set project home
@@ -263,7 +268,7 @@ function get-project-name() {
 }
 
 #
-# returns the project version as specified in the pom.xml file
+# Returns the project version as specified in the pom.xml file, at stdout
 #
 function get-version() {
 
@@ -282,7 +287,10 @@ function get-version() {
 }
 
 #
-# replaces the version string in pom.xml with the version given as argument
+# Replaces the version string in pom.xml with the version given as argument, if they are different.
+# There are cases when set version is a noop, for example when releasing the current snapshot: the
+# POM file already contains the correct version, and subsequent functions will increment it to the
+# appropriate post-release "current" version.
 #
 function set-version() {
 
@@ -295,8 +303,16 @@ function set-version() {
     [ -z "${pom_file}" ] && pom_file=${project_home}/pom.xml
     [ -f ${pom_file} ] || fail "pom.xml file ${pom_file} not found"
 
+    local current_version
+    current_version=$(get-version) || fail "failed to get the current version from pom.xm"
+
+    if [ "${version}" = "${current_version}" ]; then
+        debug "the provided version ${version} and the current pom.xml version are identical"
+        return 0
+    fi
+
     #
-    # replace the first occurrence of <version>...</version> with our version
+    # if different, replace the first occurrence of <version>...</version> with our version
     #
 
     debug "inserting version ${version}"
@@ -314,8 +330,8 @@ function set-version() {
 # gets the current version as declared in POM and computes the version for the release
 # being processed. 'mode' can be "major", "minor", "patch", "snapshot" or a full version
 # string. If a full version string is provided, the function will verify that is a valid
-# version string and the version it # specifies if newer than the current version.
-# Sends the version string at stdout.
+# version string and the version it specifies if newer than the current version. Sends
+# the version string at stdout.
 #
 function compute-release-version() {
 
@@ -384,7 +400,14 @@ function compute-release-version() {
         fi
         snapshot=""
     elif [ "${mode}" = "snapshot" ]; then
-        if [ -z "${snapshot}" ]; then
+        if [ -n "${snapshot}" ]; then
+            #
+            # the current version is a snapshot, releasing a snapshot means releasing
+            # the current snapshot we were working on and incrementing the snapshot
+            # number.
+            #
+            debug "the current snapshot ${snapshot} is being released"
+        else
             #
             # current release is a dot release, increment to the next patch snapshot 1
             #
@@ -397,11 +420,6 @@ function compute-release-version() {
             else
                 patch=$(expr ${patch} + 1) || exit 1
             fi
-        else
-            #
-            # regular snapshot
-            #
-            snapshot=$(expr ${snapshot} + 1) || exit 1
         fi
     else
         local new_version=${mode}
@@ -833,6 +851,14 @@ function build-release-zip-file() {
         fail "failed to create zip root directory ${zip_root_dir}/bin"
     cp ${artifact_path} ${zip_root_dir}/lib && \
         debug "copied $(basename ${artifact_path}) in ${zip_root_dir}/lib" || exit 1;
+
+    # copy the processed resource files into lib
+    for i in ${project_home}/src/main/resources/*; do
+        i=$(basename ${i})
+        cp ${project_home}/target/classes/${i} ${zip_root_dir}/lib && \
+            debug "${project_home}/target/classes/${i} in ${zip_root_dir}/lib" || exit 1;
+    done
+
     cp ${project_home}/src/main/bash/* ${zip_root_dir}/bin && \
         debug "copied scripts to ${zip_root_dir}/bin" || exit 1;
     configure-run-wrapper ${zip_root_dir}/bin && \
@@ -1001,7 +1027,7 @@ function do-install-release-tools() {
     #
     # these are the links to ./operations that are going to be created in ./bin
     #
-    local links="install release test";
+    local links="release build install test";
     # create symbolic links
     (cd ${bin_dir}; \
         for link in ${links}; \
@@ -1056,55 +1082,6 @@ release_date=\${release_date}
 EOF
 ) > ${project_home}/src/main/resources/VERSION
     fi
-}
-
-function do-test() {
-
-    compute-next-version ${arguments[0]} ${arguments[1]}
-}
-
-#
-# expects all its arguments in the "arguments" global array
-#
-function do-install() {
-
-    #
-    # process arguments
-    #
-
-    #
-    # options:
-    #
-    #  --force
-    #
-
-    local force=false
-
-    local i=0
-    while [ ${i} -lt ${#arguments[*]} ]; do
-        local arg=${arguments[${i}]}
-        debug "do-install arg ${i}: ${arg}"
-        if [ "${arg}" = "-f" -o "${arg}" = "--force" ]; then
-            force=true
-        fi
-        ((i++))
-    done
-
-    #
-    # checking pre-requisites
-    #
-
-    [ -z ${RUNTIME_DIR} ] && fail "RUNTIME_DIR environment variable not set, don't know where to install"
-
-    debug "checking whether the project installation zip has been built ..."
-
-    local release_zip_file_path
-    release_zip_file_path=$(build-release-zip-file) || exit 1
-
-    local installed_path
-    installed_path=$(install ${release_zip_file_path} ${RUNTIME_DIR} ${force}) || exit 1
-
-    info "installed $(basename ${installed_path}) in $(dirname ${installed_path})"
 }
 
 #
@@ -1167,6 +1144,7 @@ function do-release() {
 
     local release_version
     release_version=$(compute-release-version "${current_version}" "${mode}") || exit 1
+
     debug "release version ${release_version}"
 
     yes "releasing ${release_version}, is this OK?" || { info "release canceled, no files were changed"; return 0; }
@@ -1187,7 +1165,11 @@ function do-release() {
 
     git add . && info "git add ok" || fail "git add . failed"
 
-    git commit -m "release ${release_version}" && info "git commit ok" || fail "git commit failed"
+    #
+    # there may be nothing to commit, so we don't fail on commit failure, we just warn
+    #
+
+    git commit -m "release ${release_version}" && info "git commit ok" || warn "git commit did not succeed, maybe because there was nothing to commit"
 
     local tag=release-${release_version}
     local tagged
@@ -1222,7 +1204,10 @@ function do-release() {
             fail "release binary artifact ${release_binary_artifact} not found, something went wrong with the maven build process"
 
     else
-        mvn ${maven_testing_configuration} clean package || \
+        #
+        # we need to do install and not package because we may need the JAR in the Maven repository as well
+        #
+        mvn ${maven_testing_configuration} clean install || \
             fail "failed to pass tests, must restore the version in pom.xml to ${current_version} manually"
         release_binary_artifact=$(build-release-zip-file) || exit 1
         install-release ${release_binary_artifact}
@@ -1254,6 +1239,82 @@ function do-release() {
     info "If you want to create an official GitHub release, use tag \"${tag}\" and binary $(basename ${release_binary_artifact})."
     info "The local version has been incremented to ${next_local_version}."
     info ""
+}
+
+#
+# expects all its arguments in the "arguments" global array
+#
+function do-build() {
+
+    #
+    # process arguments
+    #
+
+    #
+    # options:
+    #
+    #  --
+    #
+
+    local force=false
+
+    local i=0
+    while [ ${i} -lt ${#arguments[*]} ]; do
+        local arg=${arguments[${i}]}
+        debug "do-build arg ${i}: ${arg}"
+        ((i++))
+    done
+
+    local release_zip_file_path
+    release_zip_file_path=$(build-release-zip-file) || exit 1
+}
+
+#
+# expects all its arguments in the "arguments" global array
+#
+function do-install() {
+
+    #
+    # process arguments
+    #
+
+    #
+    # options:
+    #
+    #  --force
+    #
+
+    local force=false
+
+    local i=0
+    while [ ${i} -lt ${#arguments[*]} ]; do
+        local arg=${arguments[${i}]}
+        debug "do-install arg ${i}: ${arg}"
+        if [ "${arg}" = "-f" -o "${arg}" = "--force" ]; then
+            force=true
+        fi
+        ((i++))
+    done
+
+    #
+    # checking pre-requisites
+    #
+
+    [ -z ${RUNTIME_DIR} ] && fail "RUNTIME_DIR environment variable not set, don't know where to install"
+
+    debug "building the releasable artifact ..."
+    local release_zip_file_path
+    release_zip_file_path=$(build-release-zip-file) || exit 1
+
+    local installed_path
+    installed_path=$(install ${release_zip_file_path} ${RUNTIME_DIR} ${force}) || exit 1
+
+    info "installed $(basename ${installed_path}) in $(dirname ${installed_path})"
+}
+
+function do-test() {
+
+    compute-next-version ${arguments[0]} ${arguments[1]}
 }
 
 main $@
