full install

diff --git a/install b/install
--- a/install
+++ b/install
@@ -129,8 +129,14 @@ function clean()
 function is-zip-available()
 {
     debug-arguments $@
-    [ -z ${project_home} ] && fail "global variable 'project_home' not defined"
-    [ -f ${project_home}/target/$(get-artifact-zip-name) ] && return 0
+    local zip_file=$1 # optional
+
+    if [ -z ${zip_file} ]; then
+        [ -z ${project_home} ] && fail "global variable 'project_home' not defined"
+        zip_file=${project_home}/target/$(get-artifact-zip-name)
+    fi
+
+    [ -f ${zip_file} ] && { debug "zip file ${zip_file} is available"; return 0; }
     return 1
 }
 
@@ -229,87 +235,79 @@ function install-locally()
 
 function install-remotely()
 {
-    local remote_environment=$1
-    fail "${FUNCNAME[0]} NOT YET IMPLEMENTED"
+    debug-arguments $@
+    local zip_file=$1
+    local remote_environment=$2
+    local force=$3
+    [ -z ${force} ] && force=false
+    [ -z ${project_home} ] && fail "${FUNCNAME[0]}: remote enviornment name not provided"
+    [ -z ${zip_file} ] && fail "${FUNCNAME[0]}: zip file not provided"
+    [ -f ${zip_file} ] || fail "${FUNCNAME[0]}: zip file ${zip_file} does not exist"
+    [ -z ${project_home} ] && fail "global variable 'project_home' not defined"
 
-#    local version=$1
-#    local environment=$2
-#    local force=$3
-#
-#    debug "install_in_remote_environment(version: ${version}, environment: ${environment}, force: ${force})"
-#
-#    [ "${version}" = "" ] && { echo "'version' not specified" 1>&2; exit 1; }
-#    [ "${environment}" = "" ] && { echo "'environment' not specified" 1>&2; exit 1; }
-#
-#    local zip_file=${project_home}/target/gld-${version}.zip
-#
-#    [ -f ${zip_file} ] || \
-#        { echo "no release zip ${zip_file} found. Specify the correct version, or if the version '${version}' is correct, run ${reldir}/make-zip" 1>&2; exit 1; }
-#
-#    local environment_file=${reldir}/environments/${environment}
-#
-#    [ -f ${environment_file} ] || { echo "environment configuration file ${environment_file} does not exist" 1>&2; exit 1; }
-#
-#    local environment_user
-#    local environment_installation_dir
-#    local environment_hosts
-#
-#    . ${environment_file}
-#
-#    [ "${environment_user}" = "" ] && \
-#        { echo "environment incorrectly configured: 'environment_user' not specfied in ${environment_file}" 1>&2; exit 1; }
-#    [ "${environment_installation_dir}" = "" ] && \
-#        { echo "environment incorrectly configured: 'environment_installation_dir' not specfied in ${environment_file}" 1>&2; exit 1; }
-#    [ "${environment_hosts}" = "" ] && \
-#        { echo "environment incorrectly configured: 'environment_hosts' not specfied in ${environment_file}" 1>&2; exit 1; }
-#
-#    for host in ${environment_hosts}; do
-#        install-over-ssh ${environment_user} ${host} ${environment_installation_dir} ${zip_file} ${force} || exit 1
-#    done
-#
-#    echo "gld-${version} installed in environment ${environment}"
+    local environment_file=${project_home}/environments/${remote_environment}
+    [ -f ${environment_file} ] || fail "environment configuration file ${environment_file} does not exist"
+
+    local user
+    local installation_dir
+    local hosts # space separate list of resolvable host names or IPs
+
+    . ${environment_file}
+
+    [ -z ${user} ] && fail "environment ${remote_environment} incorrectly configured: 'user' not specfied in ${environment_file}"
+    [ -z ${installation_dir} ] && fail "environment ${remote_environment} incorrectly configured: 'installation_dir' not specfied in ${environment_file}"
+    [ -z ${hosts} ] && fail "environment ${remote_environment} incorrectly configured: 'hosts' not specfied in ${environment_file}"
+
+    for host in ${hosts}; do
+        install-over-ssh ${user} ${host} ${installation_dir} ${zip_file} ${force} || exit 1
+    done
 }
 
 function install-over-ssh()
 {
-    fail "${FUNCNAME[0]} NOT YET IMPLEMENTED"
+    debug-arguments $@
 
-#    local user=$1
-#    local host=$2
-#    local installation_dir=$3
-#    local zip_file=$4
-#    local force=$5
-#
-#    debug "installing into ${user}@${host}"
-#
-#    [ "${user}" = "" ] && { echo "'user' not specified" 1>&2; exit 1; }
-#    [ "${host}" = "" ] && { echo "'host' not specified" 1>&2; exit 1; }
-#    [ "${installation_dir}" = "" ] && { echo "'installation_dir' not specified" 1>&2; exit 1; }
-#    [ "${zip_file}" = "" ] && { echo "'zip_file' not specified" 1>&2; exit 1; }
-#    [ -f ${zip_file} ] || { echo "${zip_file} does not exist" 1>&2; exit 1; }
-#
-#    echo "uploading artifacts to ${user}@${host} ..."
-#    scp ${zip_file} $0 ${user}@${host}:${installation_dir} || \
-#        { echo "failed to scp to ${user}@${host}:${installation_dir}" 1>2; exit 1; }
-#
-#    ${force} && force_flag="--force"
-#    ${verbose} && verbose_flag="--verbose"
-#
-#    ssh ${user}@${host} "${installation_dir}/$(basename $0) ${verbose_flag} --source ${installation_dir}/$(basename ${zip_file}) --target ${installation_dir} ${force_flag}" || \
-#        { echo "failed to execute the remote installation script on ${user}@${host}" 1>2; exit 1; }
+    local user=$1
+    local host=$2
+    local installation_dir=$3
+    local zip_file=$4
+    local force=$5
+    [ -z ${force} ] && force=false
+
+    debug "installing into ${user}@${host}"
+
+    [ -z ${user} ] && fail "'user' not specified"
+    [ -z ${host} ] && fail "'host' not specified"
+    [ -z ${installation_dir} ] && fail "'installation_dir' not specified"
+    [ -z ${zip_file} ] && fail "'zip_file' not specified"
+    [ -f ${zip_file} ] || fail "${zip_file} does not exist"
+
+    debug "uploading artifacts to ${user}@${host} ..."
+    scp ${zip_file} $0 ${user}@${host}:${installation_dir} && debug "" || fail "failed to scp to ${user}@${host}:${installation_dir}"
+
+    ${force} && force_flag="--force"
+    ${verbose} && verbose_flag="--verbose"
+
+    local ssh_command="ssh ${user}@${host} ${installation_dir}/$(basename $0) ${verbose_flag} --zip-file ${installation_dir}/$(basename ${zip_file}) --installation-dir ${installation_dir} ${force_flag}"
+    debug ${ssh_command}
+    ${ssh_command} && debug "ssh successful" || debug "failed to execute the remote installation script on ${user}@${host}"
 }
 
 function main()
 {
     local force
     local remote_environment
-    local clean
+    local clean=false
+    local zip_file
+    local installation_dir
     while [ ! -z $1 ]; do
         if [ $1 = "--help" ]; then help=true
         elif [ $1 = "--verbose" -o $1 = "-v" ]; then verbose=true;
         elif [ $1 = "--no-tests" ]; then no_tests=true;
         elif [ $1 = "--clean" ]; then clean=true;
         elif [ $1 = "--force" ]; then force=true;
+        elif [ $1 = "--zip-file" ]; then shift; zip_file=$1                 # this happens on a remote host
+        elif [ $1 = "--installation-dir" ]; then shift; installation_dir=$1 # this happens on a remote host
         elif [ -z ${remote_environment} ]; then remote_environment=$1;
         else fail "unknown argument: $1"
         fi
@@ -320,66 +318,19 @@ function main()
 
     project_home=$(dirname $0)
 
+    [ -z ${zip_file} ] && zip_file=${project_home}/target/$(get-artifact-zip-name)
+
     ${clean} && clean;
 
-    ! is-zip-available && build-zip
+    ! is-zip-available ${zip_file} && build-zip
+
+    [ -z ${installation_dir} ] && installation_dir=${RUNTIME_DIR} # this only happens locally
 
     if [ -z ${remote_environment} ]; then
-        install-locally ${project_home}/target/$(get-artifact-zip-name) ${RUNTIME_DIR} ${force}
+        install-locally ${zip_file} ${installation_dir} ${force} # this may also run remotely
     else
-        install-remotely ${remote_environment}
+        install-remotely ${project_home}/target/$(get-artifact-zip-name) ${remote_environment} ${force}
     fi
 }
 
 main $@
-
-#    while [ "$1" != "" ]; do
-#
-#        elif [ "$1" = "--source" ]; then
-#            shift
-#            source=$1
-#        elif [ "$1" = "--target" ]; then
-#            shift
-#            target=$1
-#        shift
-#    done
-#
-#    local remote_enviornment_install=false
-#    local collocated=true
-#
-#    debug "source: ${source}, version: ${version}"
-#
-#    if [ "${source}" != "" ]; then
-#
-#        # this is an installation started remotely; the zip file was uploaded and it is available locally
-#        collocated=false
-#
-#    elif [ "${version}" != "" ]; then
-#
-#         remote_enviornment_install=true
-#         source=${project_home}/target/gld-${version}.zip
-#
-#    else
-#
-#        # local installation, the source is the just built zip
-#        version=$(get_version) || exit 1
-#        source=${project_home}/target/gld-${version}.zip
-#
-#    fi
-#
-#    [ -f ${source} ] || \
-#        { echo "source file ${source} does not exist - either upload it or run ${reldir}/make-zip" 1>&2; exit 1; }
-#
-#    if [ "${target}" != "" ]; then
-#        [ ! -d ${target} ] && { echo "--target directory ${target} does not exist" 1>&2; exit 2; }
-#    else
-#        [ "${RUNTIME_DIR}" = "" ] && { echo "neither --target nor RUNTIME_DIR defined" 1>&2; exit 1; }
-#        [ ! -d ${RUNTIME_DIR} ] && { echo "RUNTIME_DIR ${RUNTIME_DIR} does not exist" 1>&2; exit 1; }
-#        target=${RUNTIME_DIR}
-#    fi
-#
-#    if ${remote_enviornment_install}; then
-#        remote_environment_install "${version}" "${enviornment}" ${force}
-#    else
-#        install ${collocated} ${source} ${target} ${force}
-#    fi
