migration to multi-module project (22)

diff --git a/release/src/main/bash/.install b/release/src/main/bash/.install
--- a/release/src/main/bash/.install
+++ b/release/src/main/bash/.install
@@ -1,3 +1,68 @@
 #!/bin/bash
 
+#
+# Installation script. To be executed on initial installation or upgrade, from the bin directory.
+#
 
+link_name=gld
+remove_older_releases=true
+
+release_directory=$(basename $(cd $(dirname $0)/..; pwd))
+
+function main() {
+
+    link-to-installation-directory
+    make-convenience-links
+    configure-user-environment
+    ${remove_older_releases} && remove-older-releases
+}
+
+function link-to-installation-directory() {
+
+    local link=$(dirname $0)/../../${link_name}
+
+    if [ -h ${link} ]; then
+
+        # the link exists, must be removed
+        rm ${link} || { echo "failed to remove the old link ${link}" 1>&2; exit 1; }
+    fi
+
+    (cd $(dirname $0)/../..; ln -s ./${release_directory} ${link_name}) || \
+        { "failed to link to ${release_directory}" 1>&2; exit 1; }
+}
+
+function make-convenience-links() {
+
+    for i in build install release; do
+        (cd $(dirname $0); ln -s ./nort ${i}) || { echo "failed to link as ${i}" 1>&2; exit 1; }
+    done
+}
+
+function configure-user-environment() {
+
+    # TODO
+    echo "" > /dev/null
+}
+
+function remove-older-releases() {
+
+    for i in $(dirname $0)/../../nort-*; do
+
+        [ ! -d ${i} ] && continue
+
+        #
+        # skip ourselves
+        #
+
+        [ $(basename ${i}) = ${release_directory} ] && continue;
+
+        #
+        # remove everything else
+        #
+
+        rm -r ${i} || { echo "failed to remove older release ${i}" 1>&2; exit 1; }
+
+    done
+}
+
+main $@
diff --git a/release/src/main/bash/gld b/release/src/main/bash/gld
--- a/release/src/main/bash/gld
+++ b/release/src/main/bash/gld
@@ -1,3 +1,35 @@
 #!/bin/bash
 
+function build-classpath() {
 
+    local lib_dir=$(dirname $0)/../lib
+
+    [ -d ${lib_dir} ] || { echo "library directory ${lib_dir} not found" 1>&2; exit 1; }
+
+    local classpath="";
+
+    for i in $(find ${lib_dir} -name *.jar); do
+        [ -z "${classpath}" ] && classpath=${i} || classpath=${classpath}:${i}
+    done
+
+    [ -z "${classpath}" ] && { echo "no jar files found in ${lib_dir}" 1>&2; exit 1; }
+
+    #
+    # place the directory itself (and the log4j.xml) at the front of the classpath
+    #
+
+    classpath="${lib_dir}:${classpath}"
+
+    echo ${classpath}
+}
+
+function main() {
+
+    local classpath
+    classpath=$(build-classpath) || exit 1
+
+    echo java -cp ${classpath} io.novaordis.gld.Main
+
+}
+
+main $@
