infrastructure to run extensions (2)

diff --git a/core/release/src/main/bash/gld b/core/release/src/main/bash/gld
--- a/core/release/src/main/bash/gld
+++ b/core/release/src/main/bash/gld
@@ -8,7 +8,7 @@ function build-classpath() {
 
     local lib_dir=$(dirname $0)/../lib
 
-    [ -d ${lib_dir} ] || { echo "library directory ${lib_dir} not found" 1>&2; exit 1; }
+    [ -d ${lib_dir} ] || { echo "[error]: library directory ${lib_dir} not found" 1>&2; exit 1; }
 
     local classpath="";
 
@@ -16,22 +16,19 @@ function build-classpath() {
         [ -z "${classpath}" ] && classpath=${i} || classpath=${classpath}:${i}
     done
 
-    [ -z "${classpath}" ] && { echo "no jar files found in ${lib_dir}" 1>&2; exit 1; }
+    [ -z "${classpath}" ] && { echo "[error]: no jar files found in ${lib_dir}" 1>&2; exit 1; }
 
     local extensions_dir=$(dirname $0)/../extensions
 
-    if [ ! -d ${extensions_dir} ]; then
+    [ -d ${extensions_dir} ] || { echo "[error]: extension directory ${extensions_dir} not found" 1>&2; exit 1; }
 
-        echo "[warn]: extensions directory ${extensions_dir} not found" 1>&2
+    #
+    # add the extension JARs
+    #
 
-    else
-
-        #
-        # add the extension JARs
-        #
-
-        echo "....."
-    fi
+    for i in $(find ${extensions_dir} -mindepth 1 -maxdepth 1 -type d); do
+        classpath="${classpath}:$(get-extension-jars ${i})" || exit 1
+    done
 
     #
     # place the directory itself (and the log4j.xml) at the front of the classpath
@@ -40,6 +37,32 @@ function build-classpath() {
     classpath="${lib_dir}:${classpath}"
 
     echo ${classpath}
+}
+
+#
+# interprets the directory it gets as argument as an extension directory and returns the appropriate
+# JARs in a classpath fragment format
+#
+function get-extension-jars() {
+
+    local extension_dir=$1
+
+    [ -z "${extension_dir}" ] && { echo "extension directory not provided" 1>&2; exit 1; }
+    [ -d "${extension_dir}" ] || { echo "invalid extension directory ${extension_dir}" 1>&2; exit 1; }
+
+    #
+    # add the extension jar from the root of the extension directory earlier on the classpath
+    #
+
+    local extension_classpath
+
+    for i in $(find ${extension_dir} -name *.jar); do
+        [ -z "${extension_classpath}" ] && \
+            extension_classpath=${i} || \
+            extension_classpath=${extension_classpath}:${i}
+    done
+
+    echo ${extension_classpath}
 }
 
 function main() {
