work on background execution and remote control

diff --git a/src/main/bash/gld b/src/main/bash/gld
--- a/src/main/bash/gld
+++ b/src/main/bash/gld
@@ -52,11 +52,31 @@ function get_classpath()
     done
 }
 
-# may return empty string
+# may return empty string or more than one PID (in a space separated list)
 function get-gld-pids()
 {
     pids=$(ps -ef | grep java | grep com.novaordis.gld.Main | awk '{print $2}')
     echo ${pids}
+}
+
+#
+# gets the pids as positional arguments. If the list is empty, attempt to detect and stop all processes
+#
+function stop()
+{
+    local pids
+
+    while [ -n "$1" ]; do [ "${pids}" = "" ] && pids=$1 || pids="${pids} $1"; shift; done
+
+    if [ "${pids}" = "" ]; then
+        pids=$(get-gld-pids) || fail "failed to get gld pids"
+    fi
+
+    [ -z "${pids}" ] && { echo "no gld processes running on the system"; exit 0; }
+
+    for pid in ${pids}; do
+        kill ${pid} && echo "stopped gld (${pid})" || echo "fail to stop gld with pid ${pid}"
+    done
 }
 
 debug_args=""
@@ -70,22 +90,20 @@ while [ "$1" != "" ]; do
         verbose=true
     elif [ "$1" = "--verbose" ]; then
         verbose=true
-    elif [ "$1" = "kill" ]; then
-        do_kill=true
-#        if [ "$1" = "start" ]; then
-#            #
-#            # start in background mode
-#            #
-#            background=true;
-#        fi
+    elif [ "$1" = "--background" ]; then
+        background=true
+        args="${args} $1"
+    elif [ "$1" = "stop" ]; then
+        shift;
+        stop $@ && exit 0 || exit 1
     else
         args="${args} $1"
     fi
     shift;
 done
 
-java_home=$(get_java_home) || { echo "failed to get JAVA_HOME"; exit 1; }
-classpath=$(get_classpath) || { echo "failed to build classpath"; exit 1; }
+java_home=$(get_java_home) || fail "failed to get JAVA_HOME"
+classpath=$(get_classpath) || fail "failed to build classpath"
 
 if ${do_kill}; then
     #
@@ -105,8 +123,9 @@ command="${java_bin} -Xms${memory} -Xmx${memory} -cp ${classpath} ${debug_args} 
 ${verbose} && echo "${command}" 1>&2;
 
 if ${background}; then
-    # TODO background does not work well yet, use load, not start
-    echo "gld launched in background, use gld stop|status to interact with it"
+    ${command} &
+    pid=$!
+    echo "gld launched in background (pid ${pid}), use gld stop|status to interact with it"
 else
     ${command}
 fi
